apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngx-rb-lbe
spec:
  selector:
    matchLabels:
      app: ngx-rb-lbe
  replicas: 1 
  template:
    metadata:
      labels:
        app: ngx-rb-lbe
    spec:
      containers:
      - name: lbe
        image: 245095557466.dkr.ecr.us-east-2.amazonaws.com/lbe:34.2
        ports:
        - containerPort: 80
        readinessProbe:
          initialDelaySeconds: 15
          timeoutSeconds: 5
          httpGet:
            path: /
            port: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 3

---
apiVersion: v1
kind: Service
metadata:
  name: lbe-srv
spec:
  #type: ClusterIP
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ngx-rb-lbe