apiVersion: apps/v1
kind: Deployment
metadata:
  name: rb-red
spec:
  selector:
    matchLabels:
      app: rb-red
  replicas: 1 
  template:
    metadata:
      labels:
        app: rb-red
    spec:
      containers:
      - name: red
        image: 245095557466.dkr.ecr.us-east-2.amazonaws.com/red:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: redsrv
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: rb-red